#!/bin/bash

# Configurar botones del pad
xsetwacom set "Wacom Intuos S Pad pad" "Button" "1" "key +ctrl +z -z -ctrl"
xsetwacom set "Wacom Intuos S Pad pad" "Button" "2" "key +ctrl +shift +z -z -shift -ctrl"
xsetwacom set "Wacom Intuos S Pad pad" "Button" "3" "key +ctrl +KP_Add -KP_Add -ctrl"   # + se configura como KP_Add (teclado numérico)
xsetwacom set "Wacom Intuos S Pad pad" "Button" "8" "key +ctrl +KP_Subtract -KP_Subtract -ctrl"

# Configurar botón del stylus
xsetwacom set "Wacom Intuos S Pen stylus" "Button" "1" "button +1"
xsetwacom set "Wacom Intuos S Pen stylus" "Button" "2" "button +2"
xsetwacom set "Wacom Intuos S Pen stylus" "Button" "3" "button +3"
echo "Configuración aplicada con éxito."
